/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/aliyun_models/energy_brain_spinner.glb
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF(
    '/aliyun_models/energy_brain_spinner.glb',
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Energy_Brain_Spinner.geometry}
        material={nodes.Energy_Brain_Spinner.material}
        position={[-0.71, 0.28, -0.17]}
      />
    </group>
  );
}

useGLTF.preload('/energy_brain_spinner.glb');
