/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/aliyun_models/energy_prod.glb
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/aliyun_models/energy_prod.glb');
  return (
    <group {...props} dispose={null}>
      <group position={[-0.71, 0.29, -0.29]}>
        <mesh
          geometry={nodes.Energy_Prod_1.geometry}
          material={nodes.Energy_Prod_1.material}
        />
        <mesh
          geometry={nodes.Energy_Prod_2.geometry}
          material={nodes.Energy_Prod_2.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/energy_prod.glb');
